import { FileText, Download } from 'lucide-react';

export function Reports() {
  return (
    <div className="space-y-6">
      <header className="mb-8">
        <h1 className="text-3xl font-bold text-text">Generated Reports</h1>
        <p className="text-textMuted">Executive summaries authored by Gemma</p>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {[1, 2, 3, 4].map((i) => (
          <div key={i} className="glass-card p-6 flex flex-col justify-between h-48">
            <div>
              <div className="flex justify-between items-start mb-4">
                <div className="p-3 bg-blue-500/10 rounded-lg">
                  <FileText className="text-blue-400 w-6 h-6" />
                </div>
                <span className="text-xs font-medium px-2 py-1 bg-slate-800 rounded-full text-textMuted">
                  PDF Export
                </span>
              </div>
              <h3 className="font-bold text-lg">Department Q{i} Audit</h3>
              <p className="text-sm text-textMuted mt-1">Generated by Gemma on Nov 12, 2026</p>
            </div>
            <button className="flex items-center gap-2 text-sm text-blue-400 hover:text-blue-300 transition-colors font-medium">
              <Download className="w-4 h-4" /> Download Report
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
